name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "award"
  color: "purple"

- name: Auto reviews
  uses: golfzaptw/action-auto-reviews-from-branches@1.2.1
